# Generated by Django 5.0.6 on 2024-06-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='nest',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=40),
        ),
    ]
